### ISSUE TITLE
Two additions to the OR-WE-514 register list

### ISSUE THREAD

**Issue by FerdiEgb** [gituser-rk/orno-modbus-mqtt#1]
High byte at 111H contains the parity of the communication where 1=none, 2=odd and 3=even.
Additional word for date/time at 8120H (4 registers, 8 bytes) contains the day of the week in its high byte where 1 = Monday up to 7 = Sunday both in read/write. Only seen for 4 and 5, others not tested.

**Comment by FerdiEgb** [comment]
BTW thanks for the list, not easy to find anything about the OR-WE-514 registers on the Internet!

**Comment by FerdiEgb** [comment]
In addition, day of week = 8 seems to be an error code if the date or time can't be translated to a weekday. That is the case at power startup when the system day of the month is over 31...

Can't test any further, as the system clock of the device doesn't start after startup or downloading the computer system time. TME/DHL will pick it up any day now.

One question: do you know of any possibility to restore the default factory settings, several vendors of similar devices have that possibility included in the case of wrong programming, I have not seen that for the OR-WE-514...

**Comment by gituser-rk** [comment]
FerdiEgb, thanks for your contribution. I have no information about a factory reset or similar procedure.

**Comment by FerdiEgb** [comment]
Thanks!

Case closed...
